# Generated by Django 3.1.4 on 2020-12-12 17:19

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('source', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'STARTED'), (10, 'FINISHED'), (20, 'DELETED')], default=app.models.GameStatus['STARTED'])),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('left_current_rating', models.FloatField()),
                ('right_current_rating', models.FloatField()),
                ('left_new_rating', models.FloatField(null=True)),
                ('right_new_rating', models.FloatField(null=True)),
                ('initial_thresholds', models.BinaryField(blank=True, null=True)),
                ('left_actions', models.BinaryField(blank=True, null=True)),
                ('right_actions', models.BinaryField(blank=True, null=True)),
                ('left_rewards', models.BinaryField(blank=True, null=True)),
                ('right_rewards', models.BinaryField(blank=True, null=True)),
                ('result', models.IntegerField(choices=[(0, 'LEFT_WON'), (1, 'RIGHT_WON'), (10, 'DRAW'), (20, 'UNKNOWN')], default=app.models.GameResult['UNKNOWN'], null=True)),
                ('left_agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_l', to='app.agent')),
                ('right_agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_r', to='app.agent')),
            ],
        ),
    ]
