# Generated by Django 3.1.4 on 2020-12-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='agent',
            name='rating',
            field=models.FloatField(blank=True, default=600, null=True),
        ),
    ]
