# Generated by Django 3.1.4 on 2020-12-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201212_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='rating',
            field=models.FloatField(blank=True, default=600),
        ),
    ]
