# Generated by Django 3.1.4 on 2020-12-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201212_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
