# Generated by Django 3.1.4 on 2020-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201212_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
